---
extends:
  - airbnb-base
  - 'plugin:eslint-comments/recommended'
env:
  node: true
parserOptions:
  ecmaVersion: 9
  sourceType: script
rules:
  function-paren-newline:
    - error
    - consistent
  import/prefer-default-export: 'off'
  indent:
    - 2
    - 4
    - SwitchCase: 1
      VariableDeclarator: 1
  no-case-declarations: 'off'
  no-param-reassign: 'off'
  no-unused-vars:
    - 2
    - vars: all
      args: none
  strict:
    - error
    - safe
