service: webp-create--get-firebase-token

provider:
    name: aws
    runtime: nodejs12.x

    stage: dev
    region: us-west-2

layers:
    WebpCreateGetFirebaseToken:
        path: layers/GetFirebaseToken
        compatibleRuntimes:
            - nodejs12.x
        licenseInfo: GPLv3
        allowedAccounts:
            - '*'

functions:
    GetFirebaseToken:
        handler: handlers/index.handler
        layers:
            - { Ref: WebpCreateGetFirebaseTokenLambdaLayer}
        events:
            - http:
                  path: firebaseToken
                  method: get
                  cors: true
        environment:
            AUTH0_DOMAIN: cmc.auth0.com
            DATABASE_URL: https://video-transcoder-776cd.firebaseio.com/

resources:
    Outputs:
        ApiGatewayRestApiId:
            Value:
                Ref: ApiGatewayRestApi
            Export:
                Name: ${self:provider.stage}-${self:service}-ApiGatewayRestApiId

        ApiGatewayRestApiRootResourceId:
            Value:
                Fn::GetAtt:
                    - ApiGatewayRestApi
                    - RootResourceId
            Export:
                Name: ${self:provider.stage}-${self:service}-ApiGatewayRestApiRootResourceId
